### ISSUE TITLE
/users/id が予測可能

### ISSUE THREAD

**Issue by siotouto** [kypkyp/nuita#21]
ですがいいんですか？
いいなら閉じてくださいませ。
( https://nuita.net/users/1 へのリンクを張っている人が居るので、同様に、という )

**Comment by kypkyp** [comment]
よくない！よくないのでこのissueは開けておきます。ありがとうございます。

将来的に /users/{ハッシュ} or /users/{ID} という形にしたいと考えていますが、ルーティングの設定がややこしそうでまだ手をつけていません。
今の連番式のリンクに破壊的な変更が加わるのは確定なので、この問題はtwitter連携(#10)より先に解決する必要がありそうですね……。

**Comment by Tetsuyamin** [comment]
変更されてます？
まだ適用されてないってことですか

**Comment by kypkyp** [comment]
シュッと自動デプロイできるようにしたいね・・・

**Comment by Tetsuyamin** [comment]
あ、そういうことですか、よかったです
手動デプロイ頑張ってください

**Comment by kypkyp** [comment]
たぶんうまく行ったと思う

**Comment by Tetsuyamin** [comment]
いいかんじですね
