### ISSUE TITLE
リンクが折り返されない

### ISSUE THREAD

**Issue by Tetsuyamin** [kypkyp/nuita#28]
この方のこのヌイートのように、横幅が狭い端末上で、リンクが折り返されなくて一部しか見えないのは仕様ですか？
https://files.slack.com/files-pri/T0321RSJ5-FJLH8DKD2/ios__________.jpg

**Comment by kypkyp** [comment]
仕様じゃないです　どうにかして治します

**Comment by Muratam** [comment]
https://github.com/kypkyp/nuita/blob/master/app/assets/stylesheets/custom.scss.erb#L170 に
`word-wrap:break-word;` を追加するとか？

**Comment by Tetsuyamin** [comment]
改行されてないんじゃなくて、インデント分だけ文字列が右にずれてて余白に文字が埋まってるっぽいです
