### ISSUE TITLE
リンクを別タブで開くようにしてほしい

### ISSUE THREAD

**Issue by amool-kmc** [kypkyp/nuita#45]
自分でやれよって言われるとまあそうなんですがその方が自然というか、ユーザー的にはおかずは並んで然るべきものだと思うので

**Comment by kypkyp** [comment]
望んでないときに別タブで出てくるのめんどいので今の仕様にしましたが、他の人の意見も聞いて直したほうが良さそうなら直します
ただ、言ったり来たりが面倒なのは今のURLしか表示できない仕様に依るとこも多そうなので、twitterやSlackみたいにプレビューカード出せるようになったらある程度改善するんじゃないかなあと思います
